---
- hosts: localhost
  #gather_facts: true
  become: true

  vars_files: 
    - users.yml

  tasks:
    - name: Add Users
      user:
        name: "{{ item.key }}"
      with_dict: "{{ users }}"
    
    - name: Remove blacklisted users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      with_items: "{{ blacklisted_users }}"

    - name: Add SSH keys from Github
      authorized_key:
        user: "{{ item.key }}"
        key: "https://github.com/{{ item.value.github_username }}.keys"
      with_dict: "{{ users }}"
      when: item.value.github_username is defined

    - name: Remove Key from ec2-user
      authorized_key:
        user: "ec2-user"
        key: ""
        exclusive: yes

    - name: Configure sudoers file
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "{{ item.key }} ALL=(ALL) NOPASSWD: ALL, !/bin/su"
        validate: '/usr/sbin/visudo -cf %s'
      with_dict: "{{ users }}"

    - name: Configure Cron Entry
      lineinfile:
        line: "*/5 * * * * root ansible-pull -o -C master -d /opt/ansible -U https://github.com/venicegeo/user_demo"
        path: /etc/cron.d/ansible-pull
        state: present
        create: yes
        owner: root
        group: root
        mode: 0644
